version: "2.2"
services:
  web:
    restart: unless-stopped
    image: nginx
    ports:
    - 80:80
    #- 443:443
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  grafana:
    image: grafana/grafana
    hostname: grafana
    expose:
      - 3000
    environment: 
      GF_SECURITY_ADMIN_USER: ${ADMIN_NAME}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana

  prometheus:
    hostname: prometheus
    image: prom/prometheus 
    restart: unless-stopped
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
volumes: 
  prometheus-storage:
  grafana-storage: