{
 "title": "Splash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "time_interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests in the past minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(request_count[1m])" }
   ]
  },
  {
   "title": "Average request latency for the last $time_interval interval",
   "type": "graph",
   "description": "This graph finds the average seconds per request by using the first and last data points in the specified interval. The variable to control this is `time_interval`. More info: https://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "seconds/request" }
   ],
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[$time_interval])/rate(request_latency_seconds_count[$time_interval])"
    }
   ]
  },
  {
   "title": "Number of requests for the past $time_interval ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(request_count[$time_interval])\n"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Average request latency in the past 5 seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(request_latency_seconds_sum[10s])/irate(request_latency_seconds_count[10s])"
    }
   ]
  }
 ]
}